
Estructura de la tabla: songs
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'file_path', 'TEXT', 0, None, 0)
(2, 'title', 'TEXT', 0, None, 0)
(3, 'track_number', 'INTEGER', 0, None, 0)
(4, 'artist', 'TEXT', 0, None, 0)
(5, 'album_artist', 'TEXT', 0, None, 0)
(6, 'album', 'TEXT', 0, None, 0)
(7, 'date', 'TEXT', 0, None, 0)
(8, 'genre', 'TEXT', 0, None, 0)
(9, 'label', 'TEXT', 0, None, 0)
(10, 'mbid', 'TEXT', 0, None, 0)
(11, 'bitrate', 'INTEGER', 0, None, 0)
(12, 'bit_depth', 'INTEGER', 0, None, 0)
(13, 'sample_rate', 'INTEGER', 0, None, 0)
(14, 'last_modified', 'TIMESTAMP', 0, None, 0)
(15, 'added_timestamp', 'TIMESTAMP', 0, None, 0)
(16, 'added_week', 'INTEGER', 0, None, 0)
(17, 'added_month', 'INTEGER', 0, None, 0)
(18, 'added_year', 'INTEGER', 0, None, 0)
(19, 'duration', 'REAL', 0, None, 0)
(20, 'lyrics_id', 'INTEGER', 0, None, 0)
(21, 'replay_gain_track_gain', 'REAL', 0, None, 0)
(22, 'replay_gain_track_peak', 'REAL', 0, None, 0)
(23, 'replay_gain_album_gain', 'REAL', 0, None, 0)
(24, 'replay_gain_album_peak', 'REAL', 0, None, 0)
(25, 'album_art_path_denorm', 'TEXT', 0, None, 0)
(26, 'has_lyrics', 'INTEGER', 0, '0', 0)
(27, 'origen', 'TEXT', 0, None, 0)
(28, 'reproducciones', 'INTEGER', 0, '1', 0)
(29, 'fecha_reproducciones', 'TEXT', 0, None, 0)
(30, 'scrobbles_ids', 'TEXT', 0, None, 0)
(31, 'added_day', 'INTEGER', 0, None, 0)

Estructura de la tabla: artists
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'bio', 'TEXT', 0, None, 0)
(3, 'tags', 'TEXT', 0, None, 0)
(4, 'similar_artists', 'TEXT', 0, None, 0)
(5, 'last_updated', 'TIMESTAMP', 0, None, 0)
(6, 'origin', 'TEXT', 0, None, 0)
(7, 'formed_year', 'INTEGER', 0, None, 0)
(8, 'total_albums', 'INTEGER', 0, None, 0)
(9, 'spotify_url', 'TEXT', 0, None, 0)
(10, 'youtube_url', 'TEXT', 0, None, 0)
(11, 'musicbrainz_url', 'TEXT', 0, None, 0)
(12, 'discogs_url', 'TEXT', 0, None, 0)
(13, 'rateyourmusic_url', 'TEXT', 0, None, 0)
(14, 'links_updated', 'TIMESTAMP', 0, None, 0)
(15, 'wikipedia_url', 'TEXT', 0, None, 0)
(16, 'wikipedia_content', 'TEXT', 0, None, 0)
(17, 'wikipedia_updated', 'TIMESTAMP', 0, None, 0)
(18, 'mbid', 'TEXT', 0, None, 0)
(19, 'bandcamp_url', 'TEXT', 0, None, 0)
(20, 'member_of', 'TEXT', 0, None, 0)
(21, 'aliases', 'TEXT', 0, None, 0)
(22, 'lastfm_url', 'TEXT', 0, None, 0)
(23, 'origen', 'TEXT', 0, None, 0)
(24, 'website', 'TEXT', 0, None, 0)
(25, 'added_timestamp', 'TIMESTAMP', 0, None, 0)
(26, 'added_day', 'INTEGER', 0, None, 0)
(27, 'added_week', 'INTEGER', 0, None, 0)
(28, 'added_month', 'INTEGER', 0, None, 0)
(29, 'added_year', 'INTEGER', 0, None, 0)
(30, 'img', 'TEXT', 0, None, 0)
(31, 'img_urls', 'TEXT', 0, None, 0)
(32, 'img_paths', 'TEXT', 0, None, 0)

Estructura de la tabla: albums
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'year', 'TEXT', 0, None, 0)
(4, 'label', 'TEXT', 0, None, 0)
(5, 'genre', 'TEXT', 0, None, 0)
(6, 'total_tracks', 'INTEGER', 0, None, 0)
(7, 'album_art_path', 'TEXT', 0, None, 0)
(8, 'last_updated', 'TIMESTAMP', 0, None, 0)
(9, 'spotify_url', 'TEXT', 0, None, 0)
(10, 'spotify_id', 'TEXT', 0, None, 0)
(11, 'youtube_url', 'TEXT', 0, None, 0)
(12, 'musicbrainz_url', 'TEXT', 0, None, 0)
(13, 'discogs_url', 'TEXT', 0, None, 0)
(14, 'rateyourmusic_url', 'TEXT', 0, None, 0)
(15, 'links_updated', 'TIMESTAMP', 0, None, 0)
(16, 'wikipedia_url', 'TEXT', 0, None, 0)
(17, 'wikipedia_content', 'TEXT', 0, None, 0)
(18, 'wikipedia_updated', 'TIMESTAMP', 0, None, 0)
(19, 'mbid', 'TEXT', 0, None, 0)
(20, 'folder_path', 'TEXT', 0, None, 0)
(21, 'bitrate_range', 'TEXT', 0, None, 0)
(22, 'bandcamp_url', 'TEXT', 0, None, 0)
(23, 'producers', 'TEXT', 0, None, 0)
(24, 'engineers', 'TEXT', 0, None, 0)
(25, 'mastering_engineers', 'TEXT', 0, None, 0)
(26, 'credits', 'TEXT', 0, None, 0)
(27, 'lastfm_url', 'TEXT', 0, None, 0)
(28, 'origen', 'TEXT', 0, None, 0)
(29, 'added_timestamp', 'TIMESTAMP', 0, None, 0)
(30, 'added_day', 'INTEGER', 0, None, 0)
(31, 'added_week', 'INTEGER', 0, None, 0)
(32, 'added_month', 'INTEGER', 0, None, 0)
(33, 'added_year', 'INTEGER', 0, None, 0)
(34, 'album_art_urls', 'TEXT', 0, None, 0)

Estructura de la tabla: genres
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'description', 'TEXT', 0, None, 0)
(3, 'related_genres', 'TEXT', 0, None, 0)
(4, 'origin_year', 'INTEGER', 0, None, 0)

Estructura de la tabla: lyrics
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'track_id', 'INTEGER', 0, None, 0)
(2, 'lyrics', 'TEXT', 0, None, 0)
(3, 'source', 'TEXT', 0, "'Genius'", 0)
(4, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: song_links
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'song_id', 'INTEGER', 0, None, 0)
(2, 'spotify_url', 'TEXT', 0, None, 0)
(3, 'spotify_id', 'TEXT', 0, None, 0)
(4, 'lastfm_url', 'TEXT', 0, None, 0)
(5, 'links_updated', 'TIMESTAMP', 0, None, 0)
(6, 'youtube_url', 'TEXT', 0, None, 0)
(7, 'musicbrainz_url', 'TEXT', 0, None, 0)
(8, 'musicbrainz_recording_id', 'TEXT', 0, None, 0)
(9, 'bandcamp_url', 'TEXT', 0, None, 0)
(10, 'soundcloud_url', 'TEXT', 0, None, 0)
(11, 'boomkat_url', 'TEXT', 0, None, 0)

Estructura de la tabla: songs_fts
(0, 'title', '', 0, None, 0)
(1, 'artist', '', 0, None, 0)
(2, 'album', '', 0, None, 0)
(3, 'genre', '', 0, None, 0)

Estructura de la tabla: songs_fts_data
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'block', 'BLOB', 0, None, 0)

Estructura de la tabla: songs_fts_idx
(0, 'segid', '', 1, None, 1)
(1, 'term', '', 1, None, 2)
(2, 'pgno', '', 0, None, 0)

Estructura de la tabla: songs_fts_docsize
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'sz', 'BLOB', 0, None, 0)

Estructura de la tabla: songs_fts_config
(0, 'k', '', 1, None, 1)
(1, 'v', '', 0, None, 0)

Estructura de la tabla: song_fts
(0, 'id', '', 0, None, 0)
(1, 'title', '', 0, None, 0)
(2, 'artist', '', 0, None, 0)
(3, 'album', '', 0, None, 0)
(4, 'genre', '', 0, None, 0)

Estructura de la tabla: song_fts_data
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'block', 'BLOB', 0, None, 0)

Estructura de la tabla: song_fts_idx
(0, 'segid', '', 1, None, 1)
(1, 'term', '', 1, None, 2)
(2, 'pgno', '', 0, None, 0)

Estructura de la tabla: song_fts_content
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'c0', '', 0, None, 0)
(2, 'c1', '', 0, None, 0)
(3, 'c2', '', 0, None, 0)
(4, 'c3', '', 0, None, 0)
(5, 'c4', '', 0, None, 0)

Estructura de la tabla: song_fts_docsize
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'sz', 'BLOB', 0, None, 0)

Estructura de la tabla: song_fts_config
(0, 'k', '', 1, None, 1)
(1, 'v', '', 0, None, 0)

Estructura de la tabla: artist_fts
(0, 'id', '', 0, None, 0)
(1, 'name', '', 0, None, 0)
(2, 'bio', '', 0, None, 0)
(3, 'tags', '', 0, None, 0)

Estructura de la tabla: artist_fts_data
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'block', 'BLOB', 0, None, 0)

Estructura de la tabla: artist_fts_idx
(0, 'segid', '', 1, None, 1)
(1, 'term', '', 1, None, 2)
(2, 'pgno', '', 0, None, 0)

Estructura de la tabla: artist_fts_content
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'c0', '', 0, None, 0)
(2, 'c1', '', 0, None, 0)
(3, 'c2', '', 0, None, 0)
(4, 'c3', '', 0, None, 0)

Estructura de la tabla: artist_fts_docsize
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'sz', 'BLOB', 0, None, 0)

Estructura de la tabla: artist_fts_config
(0, 'k', '', 1, None, 1)
(1, 'v', '', 0, None, 0)

Estructura de la tabla: album_fts
(0, 'id', '', 0, None, 0)
(1, 'name', '', 0, None, 0)
(2, 'genre', '', 0, None, 0)

Estructura de la tabla: album_fts_data
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'block', 'BLOB', 0, None, 0)

Estructura de la tabla: album_fts_idx
(0, 'segid', '', 1, None, 1)
(1, 'term', '', 1, None, 2)
(2, 'pgno', '', 0, None, 0)

Estructura de la tabla: album_fts_content
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'c0', '', 0, None, 0)
(2, 'c1', '', 0, None, 0)
(3, 'c2', '', 0, None, 0)

Estructura de la tabla: album_fts_docsize
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'sz', 'BLOB', 0, None, 0)

Estructura de la tabla: album_fts_config
(0, 'k', '', 1, None, 1)
(1, 'v', '', 0, None, 0)

Estructura de la tabla: lyrics_fts
(0, 'lyrics', '', 0, None, 0)

Estructura de la tabla: lyrics_fts_data
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'block', 'BLOB', 0, None, 0)

Estructura de la tabla: lyrics_fts_idx
(0, 'segid', '', 1, None, 1)
(1, 'term', '', 1, None, 2)
(2, 'pgno', '', 0, None, 0)

Estructura de la tabla: lyrics_fts_docsize
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'sz', 'BLOB', 0, None, 0)

Estructura de la tabla: lyrics_fts_config
(0, 'k', '', 1, None, 1)
(1, 'v', '', 0, None, 0)

Estructura de la tabla: scrobbles
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'track_name', 'TEXT', 1, None, 0)
(2, 'album_name', 'TEXT', 0, None, 0)
(3, 'artist_name', 'TEXT', 1, None, 0)
(4, 'timestamp', 'INTEGER', 1, None, 0)
(5, 'scrobble_date', 'TIMESTAMP', 1, None, 0)
(6, 'lastfm_url', 'TEXT', 0, None, 0)
(7, 'song_id', 'INTEGER', 0, None, 0)
(8, 'album_id', 'INTEGER', 0, None, 0)
(9, 'artist_id', 'INTEGER', 0, None, 0)

Estructura de la tabla: lastfm_config
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'lastfm_username', 'TEXT', 0, None, 0)
(2, 'last_timestamp', 'INTEGER', 0, None, 0)
(3, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: labels
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'mbid', 'TEXT', 0, None, 0)
(3, 'founded_year', 'INTEGER', 0, None, 0)
(4, 'country', 'TEXT', 0, None, 0)
(5, 'description', 'TEXT', 0, None, 0)
(6, 'last_updated', 'TIMESTAMP', 0, None, 0)
(7, 'official_website', 'TEXT', 0, None, 0)
(8, 'wikipedia_url', 'TEXT', 0, None, 0)
(9, 'wikipedia_content', 'TEXT', 0, None, 0)
(10, 'wikipedia_updated', 'TIMESTAMP', 0, None, 0)
(11, 'discogs_url', 'TEXT', 0, None, 0)
(12, 'bandcamp_url', 'TEXT', 0, None, 0)
(13, 'mb_type', 'TEXT', 0, None, 0)
(14, 'mb_code', 'TEXT', 0, None, 0)
(15, 'mb_last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: label_relationships
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'source_label_id', 'INTEGER', 1, None, 0)
(2, 'target_label_id', 'INTEGER', 1, None, 0)
(3, 'relationship_type', 'TEXT', 1, None, 0)
(4, 'begin_date', 'TEXT', 0, None, 0)
(5, 'end_date', 'TEXT', 0, None, 0)
(6, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: label_release_relationships
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'label_id', 'INTEGER', 1, None, 0)
(2, 'album_id', 'INTEGER', 1, None, 0)
(3, 'relationship_type', 'TEXT', 1, None, 0)
(4, 'catalog_number', 'TEXT', 0, None, 0)
(5, 'begin_date', 'TEXT', 0, None, 0)
(6, 'end_date', 'TEXT', 0, None, 0)
(7, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: listenbrainz_config
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'username', 'TEXT', 0, None, 0)
(2, 'last_timestamp', 'INTEGER', 0, None, 0)
(3, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: normalized_songs
(0, 'song_id', 'INTEGER', 0, None, 1)
(1, 'normalized_title', 'TEXT', 0, None, 0)
(2, 'normalized_artist', 'TEXT', 0, None, 0)
(3, 'normalized_album', 'TEXT', 0, None, 0)

Estructura de la tabla: mb_data_songs
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'song_id', 'INTEGER', 1, None, 0)
(2, 'relationship_type', 'TEXT', 1, None, 0)
(3, 'related_mbid', 'TEXT', 1, None, 0)
(4, 'related_title', 'TEXT', 0, None, 0)
(5, 'related_artist', 'TEXT', 0, None, 0)
(6, 'relationship_direction', 'TEXT', 1, None, 0)
(7, 'last_updated', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)

Estructura de la tabla: feeds
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'entity_type', 'TEXT', 1, None, 0)
(2, 'entity_id', 'INTEGER', 1, None, 0)
(3, 'feed_name', 'TEXT', 1, None, 0)
(4, 'post_title', 'TEXT', 1, None, 0)
(5, 'post_url', 'TEXT', 1, None, 0)
(6, 'post_date', 'TIMESTAMP', 0, None, 0)
(7, 'content', 'TEXT', 0, None, 0)
(8, 'added_date', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)

Estructura de la tabla: mb_release_group
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'mbid', 'TEXT', 1, None, 0)
(2, 'title', 'TEXT', 0, None, 0)
(3, 'artist_credit', 'TEXT', 0, None, 0)
(4, 'first_release_date', 'TEXT', 0, None, 0)
(5, 'primary_type', 'TEXT', 0, None, 0)
(6, 'secondary_types', 'TEXT', 0, None, 0)
(7, 'album_id', 'INTEGER', 0, None, 0)
(8, 'artist_id', 'INTEGER', 0, None, 0)
(9, 'genre', 'TEXT', 0, None, 0)
(10, 'associated_singles', 'TEXT', 0, None, 0)
(11, 'discogs_url', 'TEXT', 0, None, 0)
(12, 'rateyourmusic_url', 'TEXT', 0, None, 0)
(13, 'allmusic_url', 'TEXT', 0, None, 0)
(14, 'wikidata_id', 'TEXT', 0, None, 0)
(15, 'last_updated', 'TIMESTAMP', 0, None, 0)
(16, 'wikipedia_url', 'TEXT', 0, None, 0)
(17, 'musicbrainz_url', 'TEXT', 0, None, 0)
(18, 'género', 'TEXT', 0, None, 0)
(19, 'apple_url', 'TEXT', 0, None, 0)
(20, 'deezer_url', 'TEXT', 0, None, 0)
(21, 'bandcamp_url', 'TEXT', 0, None, 0)
(22, 'website', 'TEXT', 0, None, 0)
(23, 'amazon_url', 'TEXT', 0, None, 0)
(24, 'metacritic_url', 'TEXT', 0, None, 0)
(25, 'caracterizado_por', 'TEXT', 0, None, 0)
(26, 'youtube_url', 'TEXT', 0, None, 0)
(27, 'spotify_url', 'TEXT', 0, None, 0)
(28, 'producer', 'TEXT', 0, None, 0)
(29, 'offiziellecharts_url', 'TEXT', 0, None, 0)
(30, 'anydecentmusic_url', 'TEXT', 0, None, 0)
(31, 'albumoftheyear_url', 'TEXT', 0, None, 0)

Estructura de la tabla: mb_wikidata
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'wikidata_id', 'TEXT', 1, None, 0)
(2, 'release_group_mbid', 'TEXT', 0, None, 0)
(3, 'album_id', 'INTEGER', 0, None, 0)
(4, 'artist_id', 'INTEGER', 0, None, 0)
(5, 'label_id', 'INTEGER', 0, None, 0)
(6, 'property_id', 'TEXT', 0, None, 0)
(7, 'property_label', 'TEXT', 0, None, 0)
(8, 'property_value', 'TEXT', 0, None, 0)
(9, 'last_updated', 'TIMESTAMP', 0, None, 0)
(10, 'value_type', 'TEXT', 0, None, 0)
(11, 'is_link', 'INTEGER', 0, '0', 0)

Estructura de la tabla: artists_networks
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 1, None, 0)
(2, 'allmusic', 'TEXT', 0, None, 0)
(3, 'bandcamp', 'TEXT', 0, None, 0)
(4, 'boomkat', 'TEXT', 0, None, 0)
(5, 'facebook', 'TEXT', 0, None, 0)
(6, 'twitter', 'TEXT', 0, None, 0)
(7, 'mastodon', 'TEXT', 0, None, 0)
(8, 'bluesky', 'TEXT', 0, None, 0)
(9, 'instagram', 'TEXT', 0, None, 0)
(10, 'spotify', 'TEXT', 0, None, 0)
(11, 'lastfm', 'TEXT', 0, None, 0)
(12, 'wikipedia', 'TEXT', 0, None, 0)
(13, 'juno', 'TEXT', 0, None, 0)
(14, 'soundcloud', 'TEXT', 0, None, 0)
(15, 'youtube', 'TEXT', 0, None, 0)
(16, 'imdb', 'TEXT', 0, None, 0)
(17, 'progarchives', 'TEXT', 0, None, 0)
(18, 'setlist_fm', 'TEXT', 0, None, 0)
(19, 'who_sampled', 'TEXT', 0, None, 0)
(20, 'vimeo', 'TEXT', 0, None, 0)
(21, 'genius', 'TEXT', 0, None, 0)
(22, 'myspace', 'TEXT', 0, None, 0)
(23, 'tumblr', 'TEXT', 0, None, 0)
(24, 'resident_advisor', 'TEXT', 0, None, 0)
(25, 'rateyourmusic', 'TEXT', 0, None, 0)
(26, 'enlaces', 'TEXT', 0, None, 0)
(27, 'last_updated', 'TIMESTAMP', 0, None, 0)
(28, 'discogs', 'TEXT', 0, None, 0)
(29, 'discogs_http', 'TEXT', 0, None, 0)

Estructura de la tabla: scrobbles_paqueradejere
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'song_id', 'INTEGER', 0, None, 0)
(2, 'track_name', 'TEXT', 1, None, 0)
(3, 'artist_name', 'TEXT', 1, None, 0)
(4, 'album_name', 'TEXT', 0, None, 0)
(5, 'artist_id', 'INTEGER', 0, None, 0)
(6, 'album_id', 'INTEGER', 0, None, 0)
(7, 'timestamp', 'INTEGER', 1, None, 0)
(8, 'scrobble_date', 'TEXT', 1, None, 0)
(9, 'lastfm_url', 'TEXT', 0, None, 0)
(10, 'fecha_adicion', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)
(11, 'artist_mbid', 'TEXT', 0, None, 0)
(12, 'name', 'TEXT', 1, None, 0)
(13, 'album_mbid', 'TEXT', 0, None, 0)
(14, 'fecha_scrobble', 'TEXT', 1, None, 0)
(15, 'reproducciones', 'INTEGER', 0, '1', 0)
(16, 'fecha_reproducciones', 'TEXT', 0, None, 0)
(17, 'youtube_url', 'TEXT', 0, None, 0)
(18, 'spotify_url', 'TEXT', 0, None, 0)
(19, 'bandcamp_url', 'TEXT', 0, None, 0)
(20, 'soundcloud_url', 'TEXT', 0, None, 0)

Estructura de la tabla: sqlite_sequence
(0, 'name', '', 0, None, 0)
(1, 'seq', '', 0, None, 0)

Estructura de la tabla: lastfm_config_paqueradejere
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'lastfm_username', 'TEXT', 0, None, 0)
(2, 'last_timestamp', 'INTEGER', 0, None, 0)
(3, 'last_updated', 'TIMESTAMP', 0, None, 0)

Estructura de la tabla: artists_setlistfm
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 1, None, 0)
(2, 'artist_name', 'TEXT', 1, None, 0)
(3, 'setlist_id', 'TEXT', 1, None, 0)
(4, 'eventDate', 'TEXT', 0, None, 0)
(5, 'artist_url', 'TEXT', 0, None, 0)
(6, 'venue_id', 'TEXT', 0, None, 0)
(7, 'venue_name', 'TEXT', 0, None, 0)
(8, 'city_name', 'TEXT', 0, None, 0)
(9, 'city_state', 'TEXT', 0, None, 0)
(10, 'coords', 'TEXT', 0, None, 0)
(11, 'country_name', 'TEXT', 0, None, 0)
(12, 'country_code', 'TEXT', 0, None, 0)
(13, 'url', 'TEXT', 0, None, 0)
(14, 'tour', 'TEXT', 0, None, 0)
(15, 'sets', 'TEXT', 0, None, 0)
(16, 'last_updated', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)

Estructura de la tabla: menciones
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 1, None, 0)
(2, 'artist_name', 'TEXT', 1, None, 0)
(3, 'feed_id', 'INTEGER', 1, None, 0)

Estructura de la tabla: discogs_discography
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 1, None, 0)
(2, 'album_id', 'INTEGER', 0, None, 0)
(3, 'album_name', 'TEXT', 1, None, 0)
(4, 'type', 'TEXT', 0, None, 0)
(5, 'main_release', 'INTEGER', 0, None, 0)
(6, 'role', 'TEXT', 0, None, 0)
(7, 'resource_url', 'TEXT', 0, None, 0)
(8, 'year', 'INTEGER', 0, None, 0)
(9, 'thumb', 'TEXT', 0, None, 0)
(10, 'stats_comm_wantlist', 'INTEGER', 0, None, 0)
(11, 'stats_comm_coll', 'INTEGER', 0, None, 0)
(12, 'user_wantlist', 'INTEGER', 0, '0', 0)
(13, 'user_coll', 'INTEGER', 0, '0', 0)
(14, 'format', 'TEXT', 0, None, 0)
(15, 'label', 'TEXT', 0, None, 0)
(16, 'status', 'TEXT', 0, None, 0)
(17, 'discogs_id', 'INTEGER', 0, None, 0)
(18, 'last_updated', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)
(19, 'uri_release', 'TEXT', 0, None, 0)
(20, 'labels', 'JSON', 0, None, 0)
(21, 'companies', 'JSON', 0, None, 0)
(22, 'formats', 'JSON', 0, None, 0)
(23, 'rating_count', 'INTEGER', 0, None, 0)
(24, 'rate_average', 'REAL', 0, None, 0)
(25, 'num_for_sale', 'INTEGER', 0, None, 0)
(26, 'lowest_price', 'REAL', 0, None, 0)
(27, 'release_title', 'TEXT', 0, None, 0)
(28, 'released', 'TEXT', 0, None, 0)
(29, 'notes', 'TEXT', 0, None, 0)
(30, 'genres', 'JSON', 0, None, 0)
(31, 'styles', 'JSON', 0, None, 0)
(32, 'tracklist', 'JSON', 0, None, 0)
(33, 'extraartists', 'JSON', 0, None, 0)
(34, 'estimated_weight', 'REAL', 0, None, 0)
(35, 'blocked_from_sale', 'INTEGER', 0, None, 0)
(36, 'is_offensive', 'INTEGER', 0, None, 0)
(37, 'images', 'JSON', 0, None, 0)

Estructura de la tabla: artists_discogs_info
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 1, None, 0)
(2, 'artist_name', 'TEXT', 0, None, 0)
(3, 'realname', 'TEXT', 0, None, 0)
(4, 'profile', 'TEXT', 0, None, 0)
(5, 'namevariations', 'TEXT', 0, None, 0)
(6, 'aliases', 'TEXT', 0, None, 0)
(7, 'groups', 'TEXT', 0, None, 0)
(8, 'url', 'TEXT', 0, None, 0)
(9, 'discogs_id', 'INTEGER', 0, None, 0)
(10, 'last_updated', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)

Estructura de la tabla: listens_guevifrito
(0, 'id', 'INT', 0, None, 0)
(1, 'track_name', 'TEXT', 0, None, 0)
(2, 'album_name', 'TEXT', 0, None, 0)
(3, 'artist_name', 'TEXT', 0, None, 0)
(4, 'timestamp', 'INT', 0, None, 0)
(5, 'listen_date', 'NUM', 0, None, 0)
(6, 'listenbrainz_url', 'TEXT', 0, None, 0)
(7, 'song_id', 'INT', 0, None, 0)
(8, 'album_id', 'INT', 0, None, 0)
(9, 'artist_id', 'INT', 0, None, 0)
(10, 'additional_data', 'TEXT', 0, None, 0)
