global_theme_config:
  enable_individual_themes: true
  font_family: Noto Fonts Emoji
  spotify_client_id: 
  spotify_client_secret: 
  spotify_redirect_uri: http://localhost:8998
  spotify_playlist_path: .content/cache/spotify_playlist_path
  lastfm_api_key: 
  lastfm_username: 
  musicbrainz_username: 
  musicbrainz_password: 
  bluesky_username: 
  bluesky_password: 
  muspy_username: 
  muspy_id: 
  muspy_password: 
  twitter_username: 
  twitter_client_id: 
  twitter_client_secret: 
  twitter_redirect_uri: http://localhost:8998
  db_path: db/sqlite/musica.sqlite
  local_playlist_path: .content/playlists/locales
  shared_db_paths:
    music_database: db/sqlite/musica.sqlite
    tt: /home/huan/Música/flac_test3.sqlite
    perico: data/moode_optimizada.sqlite
  query_db_script_path: db/tools/consultar_items_db.py
music_players:
  selelected_player:
    fuzzy: deadbeef
    url_enlaces: mpv
  installed_players:
    player_1:
      player_name: mpv
      player_path: /usr/bin/mpv
      player_temp_dir: .config/mpv/_mpv_socket
      player_config: .config/mpv/mpv.conf
      args: --input-ipc-server=/home/huan/.config/mpv/_mpv_socket
    player_2:
      player_name: mpv_no_video
      player_path: /usr/bin/mpv
      player_temp_dir: .config/mpv/_mpv_socket
      player_config: .config/mpv/mpv.conf
      args: --input-ipc-server=/home/huan/.config/mpv/_mpv_socket --no-video
    player_3:
      player_name: deadbeef
      player_path: /usr/bin/deadbeef
      player_temp_dir: false
      player_config: false
lastfm:
  enabled: true
  api_key: 
  api_secret: 
  username: 
temas:
- Tokyo Night
- Solarized Dark
- Monokai
- Catppuccin
- Dracula
- Nord
- Synthwave
tema_seleccionado: Tokyo Night
logging:
- 'true'
- 'false'
logging_state: 'false'
logging_options:
  logging_state: 'true'
  logging_level: ERROR
  log_types:
  - ERROR
  - INFO
  - WARNING
  - UI
  - DEBUG
  log_to_file: true
  log_filename: .content/logs/multi_module_manager.log
  show_module_name: true
  enable_colors: true
modules:
- name: Database Creator
  path: modules/db_creator_ui_module.py
  args:
    config_file: config/db_creator_config.json
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    tema_seleccionado: Tokyo Night
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: Config Editor
  path: modules/config_editor_module.py
  args:
    config_path: config/config.yaml
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    - Catppuccin
    - Dracula
    - Nord
    - Synthwave
    tema_seleccionado: Monokai
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: Music Browser
  path: modules/music_fuzzy_module.py
  args:
    db_path: db/sqlite/musica.sqlite
    only_local_files: 'True'
    font_family: Noto Fonts Emoji
    artist_images_dir: .content/artistas_img
    tema_seleccionado: Monokai
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    hotkeys:
      open_folder: Ctrl+O
      play_selected: Return
      spotify: Ctrl+S
      jaangle: Ctrl+J
      search_focus: Ctrl+F
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
modulos_desactivados:
- name: Conciertos
  path: modules/conciertos_module.py
  args:
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    tema_seleccionado: Tokyo Night
    config:
      country_code: ES
      artists_file: .content/artistas.txt
      apis:
        spotify:
          enabled: 'True'
        ticketmaster:
          enabled: 'True'
          api_key: 
        setlistfm:
          enabled: 'True'
          setlistfm_apikey: 
          user_agent:
            app: mfuzz
            version: 1.0
            contact: 
        muspy:
          enabled: 'True'
        songkick:
          enabled: 'False'
          api_key: TU_API_KEY_SONGKICK
        concerts_metal:
          enabled: 'True'
        rapidapi:
          enabled: 'False'
          api_key: TU_API_KEY_RAPIDAPI
        bandsintown:
          enabled: 'False'
          app_id: TU_APP_ID_BANDSINTOWN
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: Url Playlists
  path: modules/url_playlist.py
  args:
    mpv_temp_dir: .config/mpv/_mpv_socket
    pagination_value: 40
    included_services:
      bandcamp: 'True'
      lastfm: 'False'
      soundcloud: 'True'
      youtube: 'True'
      spotify: 'True'
    db_path: db/sqlite/musica.sqlite
    spotify_client_id: 
    spotify_client_secret: 
    lastfm_api_key: 
    lastfm_user: 
    playlist_unified_view: 'True'
    show_local_playlists: 'True'
    show_spotify_playlists: 'True'
    show_rss_playlists: 'True'
    urlplaylist_only_local: 'False'
    scrobbles_limit: 0
    scrobbles_by_date: 'False'
    service_priority_indices: '0'
    freshrss_url: 
    freshrss_user: 
    freshrss_api_key: 
- name: Muspy
  path: modules/muspy_releases_module.py
  args:
    db_path: db/sqlite/musica.sqlite
    query_db_script_path: db/tools/consultar_items_db.py
    search_mbid_script_path: db/enlaces_artista_album.py
    artists_file: .content/artistas.txt
    muspy_username: 
    muspy_api_key: 
    muspy_id: 
    muspy_password: 
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    tema_seleccionado: Monokai
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: Estadísticas
  path: modules/estadisticas_module.py
  args:
    db_path: db/sqlite/musica.sqlite
    tema_seleccionado: Tokyo Night
    logging:
      debug_enabled: 'True'
      log_level: INFO
      log_types: ERROR
- name: Database Editor
  path: modules/editor_module.py
  args:
    db_path: db/sqlite/musica.sqlite
    temas:
    - Tokyo Night
    - Solarized Dark
    - Monokai
    tema_seleccionado: Monokai
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: Jaangle
  path: modules/jaangle_module.py
  args:
    theme: Tokyo Night
    db_path: db/sqlite/musica.sqlite
  logging:
    debug_enabled: true
    capture_stdout: true
    log_color: '#7AA2F7'
- name: placeholder
  path: casa
