temas:
  - Tokyo Night
  - Solarized Dark
  - Monokai
  - Catppuccin
  - Dracula
  - Nord
  - Synthwave
tema_seleccionado: Catppuccin


logging:
  - "true"
  - "false"
logging_state: "false"
logging_options:
  logging_state: "true"
  logging_level: "true"
  log_types:
    - ERROR
    - INFO
    - WARNING
    - UI
    - DEBUG
  log_to_file: true
  log_filename: multi_module_manager.log
  show_module_name: true
  enable_colors: true


global_theme_config:
  enable_individual_themes: true
  font_family: Noto Fonts Emoji
  spotify_client_id: ""
  spotify_client_secret: ""
  db_path_selected: data/music.sqlite
  shared_db_paths:
    music_database: data/music.sqlite
    tt: data/moode.sqlite
    perico: data/moode_optimizada.sqlite


modules:

  - name: Url Playlists
    path: modules/url_playlist.py
    args:
      mpv_temp_dir: .config/mpv/_mpv_socket
      included_services:
        bandcamp: true
        lastfm: true
        soundcloud: true
        youtube: true
        pagination_value: 11


  - name: Music Browser
    path: modules/music_fuzzy_module.py
    args:
      db_path: data/music.sqlite
      font_family: Noto Fonts Emoji
      artist_images_dir: .content/artistas_img
      tema_seleccionado: Monokai
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      hotkeys:
        open_folder: Ctrl+O
        play_selected: Return
        spotify: Ctrl+S
        jaangle: Ctrl+J
        search_focus: Ctrl+F
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Widgets Internet
    path: modules/widget_player_module.py
    args:
      theme: Tokyo Night
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#cf7af7"

  - name: Muspy
    path: modules/muspy_releases_module.py
    args:
      db_path: data/music.sqlite
      query_db_script_path: base_datos/tools/consultar_items_db.py
      search_mbid_script_path: base_datos/enlaces_artista_album.py
      artists_file: .content/artistas.txt
      muspy_username: frodobolson@disroot.org
      muspy_api_key: ""
      muspy_password: ""
      lastfm_username: paqueradejere
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Monokai
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: LastFM Tracker
    path: modules/lastfm_scrobbler_module.py
    args:
      lastfm_api_key: ""
      lastfm_user: paqueradejere
      database_path: data/music.sqlite
      track_limit: 50
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Spotify Playlists
    path: modules/spotify_module.py
    args:
      client_id: ""
      client_secret: ""
      cache_path: .content/cache/token.txt
      force_update: "False"
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Monokai
    logging:
      debug_enabled: false
      capture_stdout: false
      log_color: "#7AA2F7"

  - name: Jaangle
    path: modules/jaangle_module.py
    args:
      theme: Tokyo Night
      db_path: data/music.sqlite
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Blogs Playlists
    path: modules/menu_blogs_module.py
    args:
      pending_dir: data/blogs_playlists/PENDIENTE
      listened_dir: data/blogs_playlists/ESCUCHADO
      local_dir: data/blogs_playlists/locales
      output_dir: data/blogs_playlists
      freshrss_url: https://freshrss.pollete.duckdns.org
      username: pollo
      auth_token: ""
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Tokyo Night
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#f77aa2"

  - name: Config Editor
    path: modules/config_editor_module.py
    args:
      config_path: config/config.yaml
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
        - Catppuccin
        - Dracula
        - Nord
        - Synthwave
      tema_seleccionado: Monokai
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

modulos_desactivados:
  - name: Script Runner
    path: modules/scripts_module.py
    args:
      config_file: scripts/menus/musica/actualizaciones/scripts_config.json
      scripts_section: available_scripts
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Monokai
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Database Editor
    path: modules/editor_module.py
    args:
      db_path: data/music.sqlite
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Monokai
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Enlaces
    path: modules/modulo_enlaces.py
    args:
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Monokai
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Conciertos
    path: modules/conciertos_module.py
    args:
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Tokyo Night
      config:
        country_code: ES
        artists_file: .content/artistas.txt
        apis:
          ticketmaster:
            enabled: "True"
            api_key: ""
          songkick:
            enabled: "False"
            api_key: TU_API_KEY_SONGKICK
          concerts_metal:
            enabled: "True"
          rapidapi:
            enabled: "False"
            api_key: TU_API_KEY_RAPIDAPI
          bandsintown:
            enabled: "False"
            app_id: TU_APP_ID_BANDSINTOWN
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"

  - name: Calendario Radicale
    path: modules/calendar_module.py
    args:
      radicale_url: https://radicale.pollete.duckdns.org
      username: pollo
      password: ""
      temas:
        - Tokyo Night
        - Solarized Dark
        - Monokai
      tema_seleccionado: Tokyo Night
    logging:
      debug_enabled: true
      capture_stdout: true
      log_color: "#7AA2F7"